## Solutions

### Exercise 1

If $ x \in S $ and $ x \in S^\perp $, then we have in particular
that $ \langle x, x \rangle = 0 $, ut then $ x = 0 $

### Exercise 2

Symmetry and idempotence of $ M $ and $ P $ can be established
using standard rules for matrix algebra. The intuition behind
idempotence of $ M $ and $ P $ is that both are orthogonal
projections. After a point is projected into a given subspace, applying
the projection again makes no difference. (A point inside the subspace
is not shifted by orthogonal projection onto that space because it is
already the closest point in the subspace to itself.)

### Exercise 3

Here’s a function that computes the orthonormal vectors using the GS
algorithm given in the lecture

In [1]:
import numpy as np

def gram_schmidt(X):
    """
    Implements Gram-Schmidt orthogonalization.

    Parameters
    ----------
    X : an n x k array with linearly independent columns

    Returns
    -------
    U : an n x k array with orthonormal columns

    """

    # Set up
    n, k = X.shape
    U = np.empty((n, k))
    I = np.eye(n)

    # The first col of U is just the normalized first col of X
    v1 = X[:,0]
    U[:, 0] = v1 / np.sqrt(np.sum(v1 * v1))

    for i in range(1, k):
        # Set up
        b = X[:, i]       # The vector we're going to project
        Z = X[:, 0:i]     # First i-1 columns of X

        # Project onto the orthogonal complement of the col span of Z
        M = I - Z @ np.linalg.inv(Z.T @ Z) @ Z.T
        u = M @ b

        # Normalize
        U[:, i] = u / np.sqrt(np.sum(u * u))

    return U

Here are the arrays we’ll work with

In [2]:
y = [1, 3, -3]

X = [[1,  0],
     [0, -6],
     [2,  2]]

X, y = [np.asarray(z) for z in (X, y)]

First let’s try projection of $ y $ onto the column space of
$ X $ using the ordinary matrix expression:

In [3]:
Py1 = X @ np.linalg.inv(X.T @ X) @ X.T @ y
Py1

array([-0.56521739,  3.26086957, -2.2173913 ])

Now let’s do the same using an orthonormal basis created from our
`gram_schmidt` function

In [4]:
U = gram_schmidt(X)
U

array([[ 0.4472136 , -0.13187609],
       [ 0.        , -0.98907071],
       [ 0.89442719,  0.06593805]])

In [5]:
Py2 = U @ U.T @ y
Py2

array([-0.56521739,  3.26086957, -2.2173913 ])

This is the same answer. So far so good. Finally, let’s try the same
thing but with the basis obtained via QR decomposition:

In [6]:
from scipy.linalg import qr

Q, R = qr(X, mode='economic')
Q

array([[-0.4472136 , -0.13187609],
       [-0.        , -0.98907071],
       [-0.89442719,  0.06593805]])

In [7]:
Py3 = Q @ Q.T @ y
Py3

array([-0.56521739,  3.26086957, -2.2173913 ])

Again, we obtain the same answer